// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace DbFirst.Entities
{
    public partial class Order
    {
        public Order()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int OrderId { get; set; }
        public Guid? Guid { get; set; }
        [Display(Name = "PO No")]
        public string OrderNo { get; set; }
        [Display(Name = "PO Date")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime? OrderDate { get; set; }
        public int? VendorId { get; set; }
        public int? OrganizationId { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? Amount { get; set; }
        public bool? Status { get; set; }
        public bool? Deleted { get; set; }
        [Display(Name = "Created By")]
        public int? CreatedBy { get; set; }
        [Display(Name = "Created On")]
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }

        public virtual Currency Currency { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}