// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DOF_POList_EFCore.Entities
{
    public partial class Order
    {
        public Order()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int OrderId { get; set; }
        public Guid? Guid { get; set; }
        public string OrderNo { get; set; }
        public DateTime? OrderDate { get; set; }
        public int? VendorId { get; set; }
        public int? UserId { get; set; }
        public int? OrganizationId { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? Amount { get; set; }
        public bool? Status { get; set; }
        public bool? Deleted { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }

        public virtual Currency Currency { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}